import { Providers } from '@/store/provider'
import { Karla } from 'next/font/google'
import '@fortawesome/fontawesome-svg-core/styles.css'


import './themes.scss'


import Overlay from '@/app/_components/common/overlay'
import { createTheme } from '@mui/material'
import Navbar from '../_components/layout/navbar'
import Footer from '../_components/layout/footer'


const karla = Karla({
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  display: 'swap',
})
export const metadata = {
  title: 'Asambleas climaticas',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children, params: { lang } }) {

  return (
    <html lang="es" className={karla.className}>
      <body>
        <Providers>
          <Navbar lang={lang} />
          <main>
            {children}
          </main>
          <Footer />
          <Overlay />


        </Providers>
      </body>
    </html>
  )
}
