import { Karla } from 'next/font/google'
import '@fortawesome/fontawesome-svg-core/styles.css'


import './themes.scss'


import Navbar from "@/components/layout/navbar"
import Footer from '@/components/layout/footer'
import AuthContextProvider from '@/context/auth-context'
import Message from '@/components/common/message'
import { AlertProvider } from '@/context/alert-context'
import { LanguageProvider } from '@/context/lang-context'
import { Providers } from '@/store/provider'


const karla = Karla({
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  display: 'swap',
})
export const metadata = {
  title: 'Asambleas climaticas',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {

  return (
    <html lang="es" className={karla.className}>
      <body>
        <Providers>
          <AuthContextProvider>
            <AlertProvider>
              <LanguageProvider>
                <Navbar />
                <main>
                  {children}
                </main>
                <Footer />
                <Message />
              </LanguageProvider>
            </AlertProvider>
          </AuthContextProvider>
        </Providers>
      </body>
    </html>
  )
}
